name: Test Binaries

on:
  repository_dispatch:
    types: [binary-build-complete]
  watch:
    types: [started]

jobs:
  test_mac_binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: E2E Mac Binary
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          pwd
          ls
          dest="s3://figgy-website/releases/cli/latest/darwin/figgy.zip"
          aws s3 cp $dest .
          unzip figgy.zip
          cd figgy
          export PATH="$PATH:$(PWD)"
          cd ..
          ls
          pwd
          cd src/

          echo "Testing MAC binary as okta user"
          python run_tests.py okta
