name: Test Binaries

on:
  repository_dispatch:
    types: [binary-build-complete]
  watch:
    types: [started]

jobs:
  test_mac_binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Mac Binary Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          FIGGY_DISABLE_KEYRING: true
          OVERRIDE_KEYRING: true
          OKTA_SSO_USER: ${{ secrets.OKTA_SSO_USER }}
          OKTA_SSO_PASSWORD: ${{ secrets.OKTA_SSO_PASSWORD }}
          OKTA_EMBED_URL: ${{ secrets.OKTA_EMBED_URL }}
          OKTA_MFA_SECRET: ${{ secrets.OKTA_MFA_SECRET }}
          DISABLE_FIGGY_METRICS: true
          FIGGY_DISABLE_VERSION_CHECK: true
          TERM: xterm-256color
        run: |
          dest="s3://figgy-website/releases/cli/unstable/darwin/figgy.zip"
          aws s3 cp $dest .
          unzip figgy.zip
          cd figgy
          export PATH="$PATH:$(PWD)"
          cd ../src

          pip install -r requirements.txt
          pip3 install -r requirements-test.txt

          echo "Testing MAC binary as okta user"
          python run_tests.py okta

  test_linux_binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install libusb-1.0-0-dev libxmu-dev libxmu-headers \
          freeglut3-dev libxext-dev libxi-dev libudev1 libudev-dev

      - name: Linux Binary Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          FIGGY_DISABLE_KEYRING: true
          OVERRIDE_KEYRING: true
          DISABLE_FIGGY_METRICS: true
          FIGGY_DISABLE_VERSION_CHECK: true
          TERM: linux
        run: |
          dest="s3://figgy-website/releases/cli/unstable/linux/figgy.zip"
          aws s3 cp $dest .
          unzip figgy.zip
          cd figgy
          export PATH="$PATH:$(pwd)"
          cd ../src

          pip install -r requirements.txt
          pip3 install -r requirements-test.txt

          echo "Testing MAC binary as okta user"
          python run_tests.py bastion

  test_windows_binary:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Windows Binary Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          FIGGY_DISABLE_KEYRING: true
          OVERRIDE_KEYRING: true
          DISABLE_FIGGY_METRICS: true
          FIGGY_DISABLE_VERSION_CHECK: true
        shell: bash
        run: |
          dest="s3://figgy-website/releases/cli/unstable/windows/figgy.zip"
          aws s3 cp $dest .
          unzip figgy.zip
          cd figgy
          export PATH="$PATH:$(PWD)"
          cd ../src

          figgy --version