name: Build & Deploy

on:
  repository_dispatch:
    types: [build-complete]

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install libusb-1.0-0-dev libxmu-dev libxmu-headers \
          freeglut3-dev libxext-dev libxi-dev libudev1 libudev-dev

      - name: Build
        env:
          DEMO_USER_MFA_SECRET: ${{ secrets.DEMO_USER_MFA_SECRET }}
          DEMO_USER_PASSWORD_OVERRIDE: ${{ secrets.DEMO_USER_PASSWORD_OVERRIDE }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y9w7q0o6
          docker build -t figgy-demo:latest -f build/demo/Dockerfile . --build-arg FIGGY_MFA_SECRET_OVERRIDE=${DEMO_USER_MFA_SECRET} --build-arg FIGGY_PASSWORD_OVERRIDE=${DEMO_USER_PASSWORD_OVERRIDE}

          docker tag figgy-demo:latest public.ecr.aws/y9w7q0o6/figgy-demo:latest
          docker push public.ecr.aws/y9w7q0o6/figgy-demo:latest



