name: E2E Integration Test Suite

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test_bastion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install libusb-1.0-0-dev libxmu-dev libxmu-headers \
          freeglut3-dev libxext-dev libxi-dev libudev1 libudev-dev

      - name: Install figgy
        run: |
          cd src
          pip install -r requirements.txt
          pip install -r requirements-linux.txt
          pip install -r requirements-test.txt
          ../scripts/install.sh

      - name: Run E2E Test Suite
        env:
          FIGGY_DISABLE_KEYRING: true
          OVERRIDE_KEYRING: true
          FIGGY_DISABLE_METRICS: true
          FIGGY_DISABLE_VERSION_CHECK: true
        run: |
          export TERM=linux
          export TERMINFO=/etc/terminfo
          cd src
          python run_tests.py bastion

#  test_google:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Python 3.8
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8
#      - name: Install dependencies
#        env:
#          FIGGY_TEST: true
#        run: |
#          sudo apt-get update \
#          && sudo apt-get install libusb-1.0-0-dev libxmu-dev libxmu-headers \
#          freeglut3-dev libxext-dev libxi-dev libudev1 libudev-dev
#
#      - name: Install figgy
#        run: |
#          cd src
#          pip install -r requirements.txt
#          pip install -r requirements-linux.txt
#          pip install -r requirements-test.txt
#          ../scripts/install.sh
#      - name: Run E2E Test Suite
#        env:
#          FIGGY_DISABLE_KEYRING: true
#          OVERRIDE_KEYRING: true
#          GOOGLE_IDP_ID: ${{ secrets.GOOGLE_IDP_ID }}
#          GOOGLE_SP_ID: ${{ secrets.GOOGLE_SP_ID }}
#          GOOGLE_SSO_PASSWORD: ${{ secrets.GOOGLE_SSO_PASSWORD }}
#          GOOGLE_SSO_USER: ${{ secrets.GOOGLE_SSO_USER }}
#          GOOGLE_MFA_SECRET: ${{ secrets.GOOGLE_MFA_SECRET }}
#          FIGGY_DISABLE_METRICS: true
#          FIGGY_DISABLE_VERSION_CHECK: true
#        run: |
#          export TERM=linux
#          export TERMINFO=/etc/terminfo
#          cd src
#          python run_tests.py google

  test_okta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        env:
          FIGGY_TEST: true
        run: |
          sudo apt-get update \
          && sudo apt-get install libusb-1.0-0-dev libxmu-dev libxmu-headers \
          freeglut3-dev libxext-dev libxi-dev libudev1 libudev-dev

      - name: Install figgy
        run: |
          cd src
          pip install -r requirements.txt
          pip install -r requirements-linux.txt
          pip install -r requirements-test.txt
          ../scripts/install.sh

      - name: Run E2E Test Suite
        env:
          FIGGY_DISABLE_KEYRING: true
          OVERRIDE_KEYRING: true
          OKTA_SSO_USER: ${{ secrets.OKTA_SSO_USER }}
          OKTA_SSO_PASSWORD: ${{ secrets.OKTA_SSO_PASSWORD }}
          OKTA_EMBED_URL: ${{ secrets.OKTA_EMBED_URL }}
          OKTA_MFA_SECRET: ${{ secrets.OKTA_MFA_SECRET }}
          FIGGY_DISABLE_METRICS: true
          FIGGY_DISABLE_VERSION_CHECK: true
        run: |
          export TERM=linux
          export TERMINFO=/etc/terminfo
          cd src
          python run_tests.py okta

  test_profile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install libusb-1.0-0-dev libxmu-dev libxmu-headers \
          freeglut3-dev libxext-dev libxi-dev libudev1 libudev-dev

      - name: Install figgy
        run: |
          cd src
          pip install -r requirements.txt
          pip install -r requirements-linux.txt
          pip install -r requirements-test.txt
          ../scripts/install.sh

      - name: Run E2E Test Suite
        env:
          FIGGY_DISABLE_KEYRING: true
          OVERRIDE_KEYRING: true
          QA_TESTER_CREDENTIALS_FILE: ${{ secrets.QA_TESTER_CREDENTIALS_FILE }}
          QA_TESTER_CONFIG_FILE: ${{ secrets.QA_TESTER_CONFIG_FILE }}
          AWS_REGION: us-east-1
          FIGGY_DISABLE_METRICS: true
          FIGGY_DISABLE_VERSION_CHECK: true
        run: |
          mkdir -p ~/.aws
          echo "$QA_TESTER_CREDENTIALS_FILE" > ~/.aws/credentials
          echo "$QA_TESTER_CONFIG_FILE" > ~/.aws/config

          cat ~/.aws/config
          export TERM=linux
          export TERMINFO=/etc/terminfo
          cd src
          python run_tests.py profile figgy-qa-tester

  emit_e2e_test_complete:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - test_bastion
      - test_okta
      - test_profile
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: figtools/figgy-cli
          event-type: e2e-tests-complete
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'